language: java
jdk:
 - oraclejdk8
install: true
addons:
  sonarqube:    
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
script:
  #1 the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - ./mvnw clean install
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: proftaak23ivh11a1b
 
