server:
  port: 8000

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org:  FINE
        
tutorial:
   client:
    duration: 60000
